### PR TITLE
Add support for numerals

### LINKED ISSUE #20: 💡 RFC: Add support for numerals (III IV)
### Background & Motivation

It's a pretty straightforward feature. Allow for Numerals to be a 'key' you can switch to.

The catch with numerals is that minor chords are lowercase and major chords are uppercase.

"ii == 2m == Gm" and "II == 2 == G"

### Detailed Design

_No response_

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

### PR DESCRIPTION
**Pull request by martijnversluis**
Add support for numerals to

- [x] `Note`
- [x] `Key`
- [x] `Chord`

Resolves #20

### CODE REVIEW

**Comment by martijnversluis** [comment]
@isaiahdahl I think this is complete now. What do you think?

**Comment by isaiahdahl** [comment]
Been reviewing along the way. Liking what I'm seeing! Thanks for all your work on this!

**Comment by isaiahdahl** [comment]
@martijnversluis  when this merged, Does this add some scope to the enharmonic rules PR?

**Comment by martijnversluis** [comment]
@isaiahdahl There is overlap with the enharmonic rules, so I'll have to rebase that and ensure it works like expected.

I decided to first finish this to better understand the concept first.

**Comment by isaiahdahl** [comment]
🎉

**Pull request merged**
